name: Go Test

on:
  push:
    branches:
      - main
      - 'dev*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - 'dev*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v
